deno add -D jsr:@std/async --allow-scripts
deno add -D jsr:@std/dotenv --allow-scripts
deno add -D jsr:@eslint/compat --allow-scripts
deno add -D npm:@eslint/js@latest --allow-scripts
deno add -D npm:@sveltejs/vite-plugin-svelte@latest --allow-scripts
deno add -D npm:@sveltejs/adapter-node@latest --allow-scripts
deno add -D npm:@tailwindcss/container-queries@latest --allow-scripts
deno add -D npm:@tailwindcss/forms@latest --allow-scripts
deno add -D npm:@tailwindcss/typography@latest --allow-scripts
deno add -D npm:eslint@latest --allow-scripts
deno add -D npm:eslint-config-prettier@latest --allow-scripts
deno add -D npm:eslint-plugin-svelte@latest --allow-scripts
deno add -D npm:globals@latest --allow-scripts
deno add -D npm:prettier@latest --allow-scripts
deno add -D npm:prettier-plugin-svelte@latest --allow-scripts
deno add -D npm:prettier-plugin-tailwindcss@latest --allow-scripts
deno add -D npm:svelte@latest --allow-scripts
deno add -D npm:svelte-check@latest --allow-scripts
deno add -D npm:tailwindcss@latest --allow-scripts
deno add -D npm:typescript-eslint@latest --allow-scripts
deno add -D npm:vite@latest --allow-scripts
deno add -D npm:unplugin-icons@latest --allow-scripts
deno add -D npm:vite-imagetools@latest --allow-scripts
deno add -D npm:@img/sharp-wasm32@latest --allow-scripts
deno add -D npm:sharp@latest --allow-scripts
deno add -D npm:@google-cloud/storage@latest --allow-scripts
deno add -D npm:@iconify/json@latest --allow-scripts
deno add -D npm:sass-embedded@latest --allow-scripts
deno add -D npm:@tailwindcss/vite@latest --allow-scripts
deno add -D npm:@sveltejs/kit@latest --allow-scripts
